#!/bin/bash

sudo yum install -y nginx
sudo mkdir -p /var/log/nginx/app
sudo chown -R nginx:nginx /var/log/nginx/app

sudo tee /etc/nginx/conf.d/health.conf << 'EOF'
server {
    listen 80;
    server_name _;
    
    location /health {
        access_log off;
        return 200 'OK\n';
        add_header Content-Type text/plain;
    }
    
    # Можно добавить заглушку для остальных запросов
    location / {
        return 404 'Not Found\n';
    }
}
EOF

sudo tee /etc/nginx/nginx.conf << 'EOF'
user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/app/access.log main;
    
    include /etc/nginx/conf.d/*.conf;
}
EOF

sudo tee /etc/logrotate.d/nginx-app << 'EOF'
/var/log/nginx/app/*.log {
    daily
    missingok
    rotate 7
    compress
    delaycompress
    notifempty
    create 0640 nginx nginx
    sharedscripts
    postrotate
        if [ -f /var/run/nginx.pid ]; then
            kill -USR1 `cat /var/run/nginx.pid`
        fi
    endscript
}
EOF

sudo systemctl start nginx
sudo systemctl enable nginx
